version: "3.8"

networks:
  paimonbank:
    driver: bridge

volumes:
  api:
  postgres_data:
  prometheus_data:
  grafana_data:

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    networks:
      - paimonbank
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-configs:/etc/grafana/provisioning:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    networks:
      - paimonbank
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
  web:
    build: .
    container_name: mainapp
    hostname: web
    restart: always
    ports:
      - "8080:8080"
    networks:
      - paimonbank
    env_file:
      - .env
    volumes:
      - api:/usr/src/app/
