{
 "title": "PaimonBank",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Saturation",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(go_goroutines{instance=\"web:8080\", job=\"my-gin-app\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_histogram_bucket{path=\"/v1/balance/\", status=\"Internal Server Error\"}[10m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(http_request_histogram_bucket{path=\"/v1/transaction\", status=\"Internal Server Error\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency P50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(http_request_histogram_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency P90",
   "type": "timeseries",
   "description": "- Route Latency P95, P90, P50\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(http_request_histogram_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_histogram_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_request_histogram_count{path=\"/v1/balance/\", status=\"OK\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(http_request_histogram_count{path=\"/v1/transaction\", status=\"OK\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(http_request_histogram_count{path=\"/v1/user/login\", status=\"OK\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}